name: Run CI Build / Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  SERVERLESS_STAGE: ci
  COGNITO_USERNAME: test_user@some.place
  COGNITO_PASSWORD: ${{ secrets.TEST_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    strategy:
      matrix:
        node-versions: [14.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: us-east-1
        role-to-assume: arn:aws:iam::354178563115:role/Pray4uBackendGithubActions
        role-session-name: Pray4uBackendGitHubDeploy

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: yarn install
      run: npx yarn install --frozen-lockfile

    - name: Run unit tests
      run: npx yarn unit-test

    - name: Serverless deploy to ci
      run: npx serverless deploy --stage ${{ env.SERVERLESS_STAGE }}

    - name: Create test user
      run: ./integration/create_test_user.sh

    - name: Wait for API Gateway
      run: npx ts-node integration/wait_for_api_to_be_ready.ts

    - name: Run integration tests
      run: npx yarn integration-test

    - name: Delete test user
      if: always()
      run: ./integration/delete_test_user.sh

    - name: Serverless remove ci
      if: always()
      run: npx serverless remove --stage ${{ env.SERVERLESS_STAGE }}

    - name: Serverless deploy to staging
      if: ${{ success() && github.ref == 'refs/heads/main' }}
      run: npx serverless deploy --stage staging
